version: '3.4'

services:
  auth.api:
    image: ${DOCKER_REGISTRY-}authapi
    container_name: auth.api
    build:
      context: .
      dockerfile: Auth.API/Dockerfile
    depends_on:
      - auth.redis
  auth.db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: auth.db
    environment:
      SA_PASSWORD: "password123"
      ACCEPT_EULA: "Y"
  auth.redis:
    image: redis:6.2-alpine
    container_name: auth.redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local